name: Test API Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Test API build
    runs-on: ubuntu-latest
    container:
      image: ermiry/cerver-cmongo:buildev-2.0b-23
    steps:
      - uses: actions/checkout@v2

      - name: Build Sources
        run: make
