name: Test Service Test

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # docker setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # test
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          tags: ermiry/test-api:test
